### ISSUE TITLE
Basic authentication is not supported.

### ISSUE THREAD

**Issue by jarekkowol** [BitBagCommerce/SyliusPayUPlugin#13]
Hello, after installation and configuration i have problem with payment. I have oauth Payu but I do not know what to do with them.

I see:

OpenPayU_Order::verifyResponse(array('code' => 401, 'response' => 'Basic authentication is not supported.'), 'OrderCreateResponse')
in vendor/openpayu/openpayu/lib/OpenPayU/v2/Order.php (line 56)

Any solution?

**Comment by bitbager** [comment]
Have you configured everything properly in your PayU admin? The error is being thrown by their internal library, and the whole plugin works for us in a project with the primary and recommended configuration.
