### ISSUE TITLE
payment status

### ISSUE THREAD

**Issue by miojamo** [BitBagCommerce/SyliusPayUPlugin#14]
I had a successful payment made with this plugin however order status shows:
State: New
Payment State: Awaiting payment

What could be the reason? Is there any log?

**Comment by bitbager** [comment]
Currently, the plugin is not switching the state automatically. It'd need something like we've done in our another payment plugin - https://github.com/BitBagCommerce/SyliusMercanetBnpParibasPlugin/blob/master/src/Action/NotifyAction.php#L72

**Comment by miojamo** [comment]
Would you add this to the payment plugin? I think it should be handled. Thanks.

**Comment by bitbager** [comment]
This is somewhere in our backlog, but in the incoming weeks, we will not find time for it unless some of our clients will really need it.
