### ISSUE TITLE
Redirect after successful payment.

### ISSUE THREAD

**Issue by jarekkowol** [BitBagCommerce/SyliusPayUPlugin#16]
After the shopping process is completed, it is redirected to the website:
**www.myshop.pl/order/XXXXXXXX** 
Although the payment was successful.
It seems to me that there should be a redirection to the thank you page

How to overwrite sylius_shop_order_show?

**Comment by bitbager** [comment]
As long as the payment is marked as not completed, you are still able to change the payment method for your order. In our plugin (the latest stable version), the payment status changes to completed on PayU API callback handled by Payum notify action. Make sure you configured your environment properly and PayU service is sending the callback to your server. Note, that it won't work on localhost, as it's impossible for Payu to send a callback to your local server.

**Comment by bitbager** [comment]
Please, close this issue if you find it resolved.

**Comment by jarekkowol** [comment]
I noticed double request at the same time:

First from our store:

/payment/capture/a8-lqUev4H290vErJJJ3zc9rZ3F_VxoJelgyKVVtam4 HTTP/1.1" 302 2407 "https://naszsklep.pl/checkout/complete"

Second from provider:

/payment/capture/a8-lqUev4H290vErJJJ3zc9rZ3F_VxoJelgyKVVtam4 HTTP/1.1" 500 59409 "https://www.platnosci.pl/np/pt/index.action"

End second request get 500:
request.CRITICAL: Uncaught PHP Exception OpenPayU_Exception_Request: "ERROR_ORDER_NOT_UNIQUE - Order with given extOrderId already exists"

Any idea?

**Comment by patrick477** [comment]
Do you have this result for every payment?

**Comment by jarekkowol** [comment]
No, sometime i get: redirect to: https://outshop.pl/order/Oj4wW8hsjM
and message: **Wystąpił nieznany problem z płatnością.** and below options to re-pay

After refresh I get message:
**Nie możesz już zmienić metody płatności dla tego zamówienia**

I remind you that the entire payment has been successful.

**Comment by jarekkowol** [comment]
I use REST API (Checkout) version of PayU.

**Comment by patrick477** [comment]
I understand that you have the latest version of the plugin  `v1.7.0`

and you get a notification about the payment status from PayU?

**Comment by jbator** [comment]
Same issue here ;(
After successful payment, payu redirects to payment selection page with message: Wystąpił nieznany problem z płatnością and options to re-pay...

I'm using both newes sylius and this plugin version.
Any clue?

**Comment by rafalmal** [comment]
Outdated issue.
