### ISSUE TITLE
Payment does not change status

### ISSUE THREAD

**Issue by miojamo** [BitBagCommerce/SyliusPayUPlugin#18]
For some reason payment does not change status any more. Can you please fix it?
Transaction has been completed but status shows Awaiting payment. Thanks

**Comment by bitbager** [comment]
Hello,

We might not find time for this issue in the incoming weeks, but we'd appreciate any PRs.

Thank you in advance! 🙂

**Comment by rafalmal** [comment]
Outdated closing.
