### ISSUE TITLE
Problem with repeat of payments

### ISSUE THREAD

**Issue by filipfonal** [BitBagCommerce/SyliusPayUPlugin#19]
I have a problem with payments. If I've been redirect to PayU and left this page (for example closing browser tab) and then try repeat payment in user panel I get error 500 with this message:

> ERROR_ORDER_NOT_UNIQUE - Order with given extOrderId already exists

Has anyone had this problem or knows how to fix it?

**Comment by wobokas** [comment]
I have exactly the same problem

**Comment by mikemix** [comment]
@bitbager ?

In the `ConvertPaymentAction` class, line 43:

    $details['extOrderId'] = uniqid((string) $payment->getNumber(), true);

Should be unique instead, not deterministic as above:

    $details['extOrderId'] = uniqid(md5(mt_rand(0, 1000000)), true);

Because PayPal's order != Sylius payment id

**Comment by senghe** [comment]
Hi. I've investigated this a bit from business perspective. Your solution with creating a new unique extOrderId may result an another bug - customer can open as many payment gateway pages as they want and perform payment multiple times for same order. I know customers can't do this intentionally, but I can see the scenario:

1. Customer is redirected to the payment gateway form and selects i.e. polish BLIK payment
2. Customer waits for the BLIK code in their application, and pays for the order using it
3. Payment gateway page doesn't respond from any reason
4. Customer thinks "Okay, so I didn't paid yet, lets start payment process again"
5. Customer goes to selecting payment method step
6. Payment method step produces new transaction with another unique extOrderId
7. Customer pays, the payment gateway responds correctly after payment

:sparkles: Customer paid twice for one order. I think better is to implement from your side a functionality of generating new transaction URL and send it to client from Customer Service process, when you're sure that Customer didn't pay the first time.
