### ISSUE TITLE
Order Missing required field

### ISSUE THREAD

**Issue by daniel8702** [BitBagCommerce/SyliusPayUPlugin#22]
Hello,
I got an error when trying to pay for the order using PayU.
Error is on the details in sylius_payment saved to the Database. 

It should be 
`
{"totalAmount":2000,"currencyCode":"PLN","extOrderId":"0000000275cb5a43a4f5b4","description":"P\u0142atno\u015b\u0107 zawiera 1 pozycji \u0142\u0105cznie z 2000","client_email":"klient@test.pl","client_id":28,"customerIp":"127.0.0.1","status":"NEW","customer":{"__initializer__":{},"__cloner__":{},"__isInitialized__":false},"locale":"pl","orderId":"WF9KL9R13K190416GUEST000P01","statusPayU":"NEW"}
`

but it is 
`
{"order":{"__initializer__":null,"__cloner__":null,"__isInitialized__":true},"customer":{"__initializer__":null,"__cloner__":null,"__isInitialized__":true},"locale":"pl"}
`

I tested it on totally new installation.

**Comment by ZZromanZZ** [comment]
Try downgrade to v1.7.1

I was solving this issue yesterday.

See https://stackoverflow.com/questions/56868726/is-sylius-payumbundle-handling-payment-details-incorrectly/

**Comment by mikemix** [comment]
@bitbager ?

**Comment by damonsson** [comment]
A possible fix is on master now. After some test on real sandbox apps, will be released.

**Comment by czechmarcin** [comment]
@daniel8702 as you are part of BitBag now, you can work on this issue 🥇

**Comment by damonsson** [comment]
He did it already :D 

Fixed in #24
