### ISSUE TITLE
Oauth error: [code=0] Cache directory not exist or not writable

### ISSUE THREAD

**Issue by mikemix** [BitBagCommerce/SyliusPayUPlugin#23]
OpenPayU requires writable cache directory which, by default LOL is inside the vendors. How did you get past this? I'm going to decorate your `OpenPayUBridge` to manually change the directory to Symfony's `var` directory.

However I strongly believe this should be configurable in any way.

Using Sylius 1.5 and your plugin @1.8

**Comment by jbator** [comment]
Same issue in Sylius 1.6 and openpayu 2.2.13

**Comment by rafalmal** [comment]
Outdated closing.
