### ISSUE TITLE
Problem with cooperation with Sylius Plus - Marketplace module

### ISSUE THREAD

**Issue by piotr-zn** [BitBagCommerce/SyliusPayUPlugin#69]
We installed the PayU module on our store with Marketplace (Sylius Plus). Unfortunately, the order cannot be completed - it does not redirect to the PayU page for payment. The system returns an error regarding an empty "order description" field in the communication with PayU.

I managed to determine that in the CaptureAction.php file, in the prepareOrder function, the line $payUdata['description'] = $order->getNumber(); returns a NULL value, which causes the error.

The order in the store is created correctly, and the payment status is set to pending.

<img width="1517" alt="Zrzut ekranu 2024-07-22 o 07 32 07" src="https://github.com/user-attachments/assets/648fd62b-2d39-49ba-a3f7-b39302c5e9aa">

**Comment by tomkalon** [comment]
**FILE:** _vendor/bitbag/payu-plugin/src/Action/CaptureAction.php_

The line should be removed:

`$payUdata['description'] = $this->paymentDescriptionProvider->getPaymentDescription($payment);`

And this piece of code should be added after line:

`$payUdata['tokenValue'] = $order->getTokenValue();`

```
  if ('primary' === $order->getMode()) {
      $description = [];
      foreach ($order->getSecondaryOrders() as $secondaryOrder) {
          $description[] = $secondaryOrder->getNumber();
      }
      $description = implode(' ', $description);
      $payUdata['description'] = $description;
  }
  else {
      $payUdata['description'] = '';
  }
```
